### ISSUE TITLE
IPs not being recorded

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/plugin-fileuploader#31]
Colour codes getting in the way, but..
> 033[90m2018-05-31T06:25:45Z#033[0m |#033[31mERRO#033[0m| #033[0mFailed to record uploader IP#033[0m #033[36merror#033[0m="sql: converting argument $1 type: unsupported type net.IP, a slice"

**Comment by vith** [comment]
I'm not able to reproduce this error locally with sqlite3.

My `uploader_ip` column gets a `BLOB` with value `0x00000000000000000000ffff7f000001` which appears to be the correct binary representation for `127.0.0.1`.

Is this happening on a deployment using mysql?

**Comment by ojamin** [comment]
yep this was seen happening with mysql
