### ISSUE TITLE
Access-Control-Allow-Origin adding multiple urls

### ISSUE THREAD

**Issue by ItsOnlyBinary** [kiwiirc/plugin-fileuploader#57]
File uploadeder is adding two domains to `Access-Control-Allow-Origin` causing browser errors

```Access to XMLHttpRequest at 'https://example.com/files/' from origin 'https://znc.example.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values 'https://znc.example.com, https://znc.example.com', but only one is allowed.```

``

**Comment by vith** [comment]
I can't reproduce this, even if I duplicate the same origin twice in the config:

```toml
CorsOrigins = [ "http://192.168.1.11:40020", "http://192.168.1.11:40020" ]
```

Maybe a reverse proxy was adding the second copy?

**Comment by ojamin** [comment]
@ItsOnlyBinary have you got reproduction steps?

**Comment by ItsOnlyBinary** [comment]
really not sure any more, I will be moving servers soon for my setup, so i will reopen it if i can reproduce the issue there.
