### ISSUE TITLE
"cannot load plugin:"

### ISSUE THREAD

**Issue by fatihtoptas** [kiwiirc/plugin-fileuploader#84]
hi, when i try to install i got following error after "go run." step;

go: extracting gopkg.in/go-playground/validator.v8 v8.18.2
go: extracting gopkg.in/yaml.v2 v2.2.2
go: extracting github.com/ugorji/go v1.1.7
go: downloading github.com/ugorji/go/codec v1.1.7
go: extracting github.com/golang/protobuf v1.3.2
go: extracting github.com/ugorji/go/codec v1.1.7
go: extracting github.com/tus/tusd v0.0.0-20190712143443-30811b6579c5
go: downloading github.com/sethgrid/pester v0.0.0-20190127155807-68a33a018ad0
go: downloading github.com/bmizerany/pat v0.0.0-20170815010413-6226ea591a40
go: downloading golang.org/x/net v0.0.0-20200226121028-0de0cce0169b
go: extracting github.com/bmizerany/pat v0.0.0-20170815010413-6226ea591a40
go: extracting github.com/sethgrid/pester v0.0.0-20190127155807-68a33a018ad0
go: extracting golang.org/x/sys v0.0.0-20190712062909-fae7ac547cb7
go: extracting github.com/mattn/go-sqlite3 v1.10.0
go: extracting golang.org/x/net v0.0.0-20200226121028-0de0cce0169b
build github.com/kiwiirc/plugin-fileuploader: cannot load plugin: cannot find module providing package plugin

**Comment by fatihtoptas** [comment]
and this is my "go env" result;

phi@de:~$ go env
GOARCH="amd64"
GOBIN="/usr/bin/go"
GOCACHE="/home/phi/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/phi/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/share/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/gcc/x86_64-linux-gnu/9"
GCCGO="/usr/bin/x86_64-linux-gnu-gccgo-9"
CC="x86_64-linux-gnu-gcc-9"
CXX="x86_64-linux-gnu-g++-9"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build394821502=/tmp/go-build -gno-record-gcc-switches -funwind-tables"

**Comment by ItsOnlyBinary** [comment]
Personally i would recommend running this as a standalone binary rather than a webircgateway plugin

`go build -o fileuploader main.go`

other than that most issues are caused by outdated golang install

might find this example .service file handy for running it standalone https://gist.github.com/ItsOnlyBinary/6a37a91bf8a83b2ab166fb0d6d55fdd6/

**Comment by fatihtoptas** [comment]
i fixed that, thanks..
