### ISSUE TITLE
CORS POLICY error with apache2 and kiwi

### ISSUE THREAD

**Issue by dumber-Chatteurs** [kiwiirc/plugin-fileuploader#99]
On kiwi console : 
`Access to XMLHttpRequest at 'https://files.mydomain.com/files' (redirected from 'https://files.mydomain.com/files/') from origin 'https://mydomain.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
     
POST https://files.mydomain.com/files net::ERR_FAILED`

On SERVER : 
`me@myserv:~/plugin-fileuploader$ go run .
12:49PM INF Loaded config file path=fileuploader.config.toml
12:49PM INF Server listening address=127.0.0.1:8088 event=startup
12:50PM WRN Unknown cors origin origin=https://mydomain.com
12:50PM WRN Unknown cors origin origin=https://mydomain.com
12:50PM WRN Unknown cors origin origin=https://mydomain.com
12:50PM WRN Unknown cors origin origin=https://mydomain.com
12:50PM WRN Unknown cors origin origin=https://mydomain.com
`

fileuploader.config.toml : 
`[Server]

ListenAddress = "127.0.0.1:8088"

BasePath = "/files"

CorsOrigins = []

TrustedReverseProxyRanges = [
        "10.0.0.0/8",
        "172.16.0.0/12",
        "192.168.0.0/16",
        "fc00::/7",
        "127.0.0.0/8",
        "::1/128",
]
`

Apache confs classic : 
`<VirtualHost *:80>
        ServerName files.mydomain.com

Header set Access-Control-Allow-Origin "*"

      ProxyPass / http://127.0.0.1:8088/
      ProxyPassReverse /files http://127.0.0.1:8088/
      ProxyPreserveHost On
      DocumentRoot /path/To/a/files/directory/files/

RewriteEngine on
RewriteCond %{SERVER_NAME} =files.mydomaine.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

`

Apache confs ssl 

`<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName files.mydomain.com

Header set Access-Control-Allow-Origin "*"

      ProxyPass / http://127.0.0.1:8088/
      ProxyPassReverse /files http://127.0.0.1:8088/
      ProxyPreserveHost On
DocumentRoot /path/To/a/files/directory/files/

RewriteEngine on

SSLCertificateFile /etc/letsencrypt/live/files.mydomain.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/files.mydomain.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
`

ISSUE blocked by CORS policy

**Comment by ItsOnlyBinary** [comment]
make sure basePath is your full url on the other side of the proxy eg `https:/example.com/files/`

make sure CorsOrigins includes the full url of your kiwiirc instance eg `https:/kiwiirc.example.com/`

make sure all paths have a trailing `/` eg `ProxyPassReverse /files/ http://127.0.0.1:8088/files/` (including the path in config.json)

Post any more questions here I will get a notification and reply

**Comment by dumber-Chatteurs** [comment]
Nice it's work but video not play in kiwi ?
